/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?



 */
public class Twelve
{
    public static int numFactors(int num) // counts the number of divisors in the number
    {
        int count = 2; // start by counting 1 and the number itself
        for(int i = 2; i < Math.floor(Math.sqrt(num)) + 1; i++){
            if(num % i == 0){
                if (i * i == num){ // the sqrt will be counted twice so correct for that
                    count++;
                }else{
                    // we can get away with this because it doesn't matter WHAT the factors are we just care that they exist
                    count+=2; // every time there is one divisor there must be another which will make the product
                }
            }
        }
        return count;
    }

    public static void main(String[] args)
    {
        int triangle = 1;// the first triangle
        int i = 2; // the next number to add

        while(numFactors(triangle) < 500){ // check if the current triangle number has more than 500 divisors
            triangle += i;
            i++;
        }
        System.out.println(triangle);
    }
}
