/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Two
{
    public static void main(String[] args)
    {
        int sum = 0;
        int currentFib = 2;
        int lastFib = 1;
        int temp;

        while(currentFib < 4e6){ // 4e6 is scientific notation for 4,000,000
            if(currentFib % 2 == 0){ // is number even?
                sum += currentFib; // if so add it to the sum
            }

            // iterate to next fibonacci number and store this one as the last
            temp = currentFib;
            currentFib += lastFib;
            lastFib = temp;
        }
        System.out.println(sum);
    }
}
